name: 'Leviathan Action'
description: 'Test your software directly on hardware using the Levaithan Testing framework'

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

    - name: Pull helper images
      id: pull-helper-images
      continue-on-error: true
      working-directory: ${{ env.LEVIATHAN_ROOT }}/
      shell: bash
      run: |
        make printenv
        make config
        make pull

    - name: Build helper images
      if: steps.pull-helper-images.outcome == 'failure'
      working-directory: ${{ env.LEVIATHAN_ROOT }}/
      shell: bash
      run: |
        make printenv
        make config
        make build

    - name: Leviathan build & test
      working-directory: ${{ env.LEVIATHAN_ROOT }}/
      shell: bash
      env:
        # TODO: Expose these as action inputs instead of environment variables
        WORKER_TYPE: ${{ env.WORKER_TYPE }}
        DEVICE_TYPE: ${{ env.DEVICE_TYPE }}
        QEMU_MEMORY: ${{ env.QEMU_MEMORY }}
        QEMU_INTERNAL_STORAGE: ${{ env.QEMU_INTERNAL_STORAGE }}
        QEMU_SECUREBOOT: ${{ env.QEMU_SECUREBOOT }}
        FLASHER_SECUREBOOT: ${{ env.FLASHER_SECUREBOOT }}
      run: |
        make printenv
        make config
        make test

    - name: Create Summary
      if: always()
      shell: bash
      run: |
        echo "### ${TEST_SUITE} Test Report"  >> $GITHUB_STEP_SUMMARY

        echo "| Total Tests | Ran | Passed | Failed | Skipped |" >> $GITHUB_STEP_SUMMARY
        echo "|-------|-----|---------|--------|--------|" >> $GITHUB_STEP_SUMMARY
        jq -r '.[0].stats | "\(.tests) 📋 | \(.ran) 🏃 |  \(.passed) ✅ | \(.failed) ❌ | \(.skipped) ⏭️"' ${REPORTS}/final-result.json >> $GITHUB_STEP_SUMMARY

        echo "#### Failed Tests" >> $GITHUB_STEP_SUMMARY
        jq -r '.[0].tests | to_entries[] | select(.value == "failed") | .key' ${REPORTS}/final-result.json >> $GITHUB_STEP_SUMMARY

        echo "#### Skipped Tests" >> $GITHUB_STEP_SUMMARY
        jq -r '.[0].tests | to_entries[] | select(.value == "skipped") | .key' ${REPORTS}/final-result.json >> $GITHUB_STEP_SUMMARY

    - name: Generate artifact name
      shell: bash
      if: always()
      id: report-name
      env:
        # TODO: Expose these as action inputs instead of environment variables
        WORKER_TYPE: ${{ env.WORKER_TYPE }}
        DEVICE_TYPE: ${{ env.DEVICE_TYPE }}
        TEST_SUITE: ${{ env.TEST_SUITE }}
        QEMU_SECUREBOOT: ${{ env.QEMU_SECUREBOOT }}
      run: |
        if [ "$QEMU_SECUREBOOT" -eq 1 ]; then
          SB="-sb"
        else
          SB=""
        fi

        echo "reportName=reports-${{ env.WORKER_TYPE }}-${{ env.DEVICE_TYPE }}-${{ env.TEST_SUITE }}${SB}" >>"${GITHUB_OUTPUT}"

    - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
      if: always()
      with:
        if-no-files-found: error
        retention-days: 7
        compression-level: 7
        name: ${{ steps.report-name.outputs.reportName }}
        path: ${{ env.REPORTS }}

    - name: Teardown
      if: always()
      continue-on-error: true
      shell: bash
      working-directory: ${{ env.LEVIATHAN_ROOT }}
      run: |
        make down
