version: "2"

volumes:
  swtpm:

services:
  swtpm:
    build: swtpm
    restart: always
    volumes:
      - swtpm:/var/tpm0
    tmpfs:
      - /tmp
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        mkdir -p /tmp/tpm0
        while true; do
          swtpm socket \
            --tpmstate dir=/tmp/tpm0 \
            --ctrl type=unixio,path=/var/tpm0/swtpm.sock \
            --tpm2
        done

  worker:
    volumes:
      - "swtpm:/var/tpm0"
    depends_on:
      - swtpm
    environment:
      - QEMU_SECUREBOOT=1
