version: "2"

services:
  client:
    build: ./client
    network_mode: host
    volumes:
      - "${WORKSPACE:-./workspace}:/usr/src/app/workspace:ro"
      - "${REPORTS:-./workspace/reports}:/usr/src/app/reports:rw"
      - "${SUITES:-./suites}:/usr/src/app/suites:ro"
      - core-storage:/data
    environment:
      - WORKER_TYPE=${WORKER_TYPE}
      - DEVICE_TYPE=${DEVICE_TYPE}
      - BALENACLOUD_API_KEY=${BALENACLOUD_API_KEY}
      - BALENACLOUD_ORG=${BALENACLOUD_ORG}
      - BALENACLOUD_APP_NAME=${BALENACLOUD_APP_NAME}
      - CORE_HOST=localhost
    depends_on:
      - core

  core:
    privileged: true # preload requires docker-in-docker
    #build: core
    image: bh.cr/gh_rcooke_warwick/leviathan-core-armv7hf
    network_mode: host
    volumes:
      - core-storage:/data
      - reports-storage:/reports
    tmpfs:
      - /var/run # use tmpfs docker-in-docker pid files
      - /var/lib/docker # use tmpfs for docker-in-docker data root
    restart: 'no'

  worker:
    image: bh.cr/gh_rcooke_warwick/leviathan-worker-amrv7hf
    privileged: true
    pid: host
    network_mode: host
    ipc: host
    volumes:
      - 'core-storage:/data'
      - 'reports-storage:/reports'
      - /host/run/dbus:/host/run/dbus
      - /lib/modules:/lib/modules
    environment:
      - UDEV=1
      - BALENA_API_KEY=${BALENA_API_KEY}
      - WORKER_TYPE=autokit
      - DIGITAL_RELAY=dummyPower
      - TESTBOT_DUT_TYPE=raspberrypi4-64

volumes:
  core-storage:
  reports-storage:



