version: "2"

services:
  worker:
    image: bh.cr/balena/leviathan-worker-${BALENA_ARCH:-amd64}/${WORKER_RELEASE:-2.6.13}
    network_mode: host
    volumes:
      - "core-storage:/data"
      - "reports-storage:/reports"
    environment:
      - UDEV=0
      - WORKER_TYPE=qemu
      - SCREEN_CAPTURE=true
      - WORKER_PORT # default 80 and must match client config.js workers
      - QEMU_ARCH=${QEMU_ARCH:-x86_64}
      - QEMU_CPUS=${QEMU_CPUS}
      - QEMU_MEMORY=${QEMU_MEMORY}
      - QEMU_DEBUG=${QEMU_DEBUG}
    restart: 'no'

  core:
    privileged: true # preload requires docker-in-docker
    build: core
    network_mode: host
    volumes:
      - core-storage:/data
      - reports-storage:/reports
    tmpfs:
      - /var/run # use tmpfs docker-in-docker pid files
      - /var/lib/docker # use tmpfs for docker-in-docker data root
    restart: 'no'